/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=WorkerEnv` (hash: 3cc429446fe8cd36111a33a82ea8dac7)
interface __BaseEnv_WorkerEnv {
	OAUTH_KV: KVNamespace;
	ASSETS: Fetcher;
	SIMKL_API_BASE_URL: "https://api.simkl.com";
	MCP_OBJECT: DurableObjectNamespace<import("./src/index").SimklMCP>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "SimklMCP";
	}
	interface Env extends __BaseEnv_WorkerEnv {}
}
interface WorkerEnv extends __BaseEnv_WorkerEnv {}
